import type { Metadata } from "next";
import "@/styles/globals.css";
import { geistMono, geistSans, inter } from "@/styles/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative h-full ${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        <main className="relative flex min-h-screen flex-col">{children}</main>
      </body>
    </html>
  );
}
