import type { Metadata } from "next";
import { geistMono, geistSans, inter } from "@/config/fonts";
import { cn } from "@/utils/cn";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          (cn("relative h-full antialiased"),
          geistSans.variable,
          geistMono.variable,
          inter.variable)
        }
      >
        <main className="relative flex min-h-screen flex-col bg-white">
          {children}
        </main>
      </body>
    </html>
  );
}
